(() => {
const {loadData,saveData,resetStats}=window.TamStorage,Feedback=window.TamFeedback,Game=window.TamGame;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],data=loadData(),feedback=new Feedback(data);let toastTimer,currentMode="classic",lastSummary=null;
const screens={menu:$("#menuScreen"),game:$("#gameScreen"),settings:$("#settingsScreen"),stats:$("#statsScreen"),modes:$("#modesScreen"),tutorial:$("#tutorialScreen"),gameOver:$("#gameOverScreen")};
const elements={canvas:$("#gameCanvas"),arena:$("#arena"),score:$("#scoreValue"),round:$("#roundValue"),combo:$("#comboValue"),comboFill:$("#comboFill"),energy:$("#energy"),timer:$("#timerValue"),modeLabel:$("#modeLabel"),missionCard:$("#missionCard"),missionKicker:$("#missionKicker"),missionText:$("#missionText"),roundType:$("#roundType"),resultCard:$("#resultCard"),resultLabel:$("#resultLabel"),resultTiming:$("#resultTiming"),resultPoints:$("#resultPoints")};
const ACHIEVEMENTS=[
  {id:"firstPerfect",icon:"✦",title:"İlk Tam İsabet",desc:"İlk kusursuz dokunuşunu yap",test:d=>d.totalPerfectHits>=1},
  {id:"perfect25",icon:"◇",title:"Keskin Zamanlama",desc:"25 Tam İsabet yap",test:d=>d.totalPerfectHits>=25},
  {id:"combo10",icon:"↗",title:"Zaman Ustası",desc:"10 turluk seri yakala",test:d=>d.bestCombo>=10},
  {id:"century",icon:"100",title:"Tecrübeli",desc:"100 tur tamamla",test:d=>d.totalRounds>=100},
  {id:"explorer",icon:"◎",title:"Tur Kaşifi",desc:"50 tur türünün hepsini oyna",test:d=>Object.keys(d.roundTypeCounts||{}).length>=50},
  {id:"allModes",icon:"▦",title:"Çok Yönlü",desc:"Dört oyun modunu da oyna",test:d=>Object.values(d.gamesByMode||{}).every(v=>v>0)},
  {id:"daily",icon:"◫",title:"Günün İsabeti",desc:"Bir günlük görevi tamamla",test:d=>Boolean(d.dailyChallenge?.claimed)}
];
const MODE_NAMES={classic:"Klasik",streak:"İsabet Serisi",timed:"60 Saniye",daily:"Günlük İsabet"};
function localDateKey(){const d=new Date(),p=n=>String(n).padStart(2,"0");return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`;}
function ensureDailyTask(){const date=localDateKey();if(data.dailyChallenge?.date===date)return;const hash=[...date].reduce((a,c)=>a+c.charCodeAt(0),0),tasks=[{type:"perfect",target:3,text:"3 Tam İsabet yap"},{type:"rounds",target:12,text:"12 tur tamamla"},{type:"score",target:6000,text:"Tek oyunda 6.000 puana ulaş"}];data.dailyChallenge={date,...tasks[hash%tasks.length],progress:0,claimed:false};}
function showScreen(name){Object.entries(screens).forEach(([key,screen])=>screen.classList.toggle("active",key===name));}
function toast(message){clearTimeout(toastTimer);$("#toast").textContent=message;$("#toast").classList.add("show");toastTimer=setTimeout(()=>$("#toast").classList.remove("show"),2100);}
function checkAchievements(){let unlocked="";for(const item of ACHIEVEMENTS){if(!data.achievements[item.id]&&item.test(data)){data.achievements[item.id]=Date.now();unlocked=item.title;}}if(unlocked)toast(`Başarım açıldı: ${unlocked}`);}
function applySettings(){
  $("#soundToggle").checked=data.soundEnabled;$("#vibrationToggle").checked=data.vibrationEnabled;$("#contrastToggle").checked=data.highContrast;$("#motionToggle").checked=data.reducedMotion;$("#quickSoundBtn").classList.toggle("off",!data.soundEnabled);$("#quickSoundBtn").textContent=data.soundEnabled?"♪":"×";document.body.classList.toggle("high-contrast",data.highContrast);document.body.classList.toggle("reduced-motion",data.reducedMotion);document.body.dataset.theme=data.theme||"neon";$$('button[data-theme]').forEach(button=>button.classList.toggle("active",button.dataset.theme===data.theme));$$('[data-target]').forEach(button=>button.classList.toggle("active",button.dataset.target===data.targetStyle));
}
function renderStats(){
  ensureDailyTask();const average=data.measuredTouches?Math.round(data.totalDifference/data.measuredTouches):0;$("#menuHighScore").textContent=(data.highScore||0).toLocaleString("tr-TR");$("#statHighScore").textContent=(data.highScore||0).toLocaleString("tr-TR");$("#statGames").textContent=data.totalGames||0;$("#statRounds").textContent=data.totalRounds||0;$("#statPerfect").textContent=data.totalPerfectHits||0;$("#statCombo").textContent=data.bestCombo||0;$("#statAverage").textContent=average?`${average} ms`:"—";$("#statBalance").textContent=`${data.earlyTouches||0} / ${data.lateTouches||0}`;$("#statTimed").textContent=(data.timedHighScore||0).toLocaleString("tr-TR");$("#statStreak").textContent=data.bestStreak||0;
  const task=data.dailyChallenge;$("#dailyTaskText").textContent=task.text;$("#dailyTaskProgress").textContent=task.claimed?"TAMAMLANDI":`${Math.min(task.progress,task.target).toLocaleString("tr-TR")} / ${task.target.toLocaleString("tr-TR")}`;$("#dailyCard").classList.toggle("complete",task.claimed);$("#menuHint").textContent=task.claimed?"Günlük görev tamamlandı ✦":`Günlük: ${task.text}`;
  $("#achievementList").innerHTML=ACHIEVEMENTS.map(item=>`<div class="achievement ${data.achievements[item.id]?"unlocked":""}"><span>${item.icon}</span><div><strong>${item.title}</strong><small>${item.desc}</small></div><b>${data.achievements[item.id]?"AÇILDI":"KİLİTLİ"}</b></div>`).join("");
}
function persist(){ensureDailyTask();checkAchievements();saveData(data);renderStats();}
const game=new Game({elements,data,feedback,onStatsChange:persist,onFinish:(summary,tutorial)=>{if(tutorial){data.tutorialCompleted=true;persist();showScreen("menu");toast("Hazırsın. Tam İsabet zamanı!");return;}finishGame(summary);}});
function startMode(mode){
  currentMode=mode;feedback.unlock();$("#pauseOverlay").classList.remove("show");if(!data.tutorialCompleted&&mode==="classic"){showScreen("tutorial");return;}showScreen("game");game.start({mode,seed:mode==="daily"?localDateKey():""});
}
function startTutorial(){feedback.unlock();$("#pauseOverlay").classList.remove("show");showScreen("game");game.start({tutorial:true});}
function finishGame(summary){
  lastSummary=summary;data.totalGames=(data.totalGames||0)+1;data.gamesByMode[summary.mode]=(data.gamesByMode[summary.mode]||0)+1;let newRecord=false;
  if(summary.mode==="classic"&&summary.score>data.highScore){data.highScore=summary.score;newRecord=true;}if(summary.mode==="timed"&&summary.score>data.timedHighScore){data.timedHighScore=summary.score;newRecord=true;}if(summary.mode==="streak"&&summary.bestPerfectCombo>data.bestStreak){data.bestStreak=summary.bestPerfectCombo;newRecord=true;}if(summary.mode==="daily"){const key=localDateKey(),previous=data.dailyScores[key]||0;if(summary.score>previous){data.dailyScores[key]=summary.score;newRecord=true;}}
  persist();$("#recordLabel").textContent=newRecord?"YENİ REKOR!":`${MODE_NAMES[summary.mode].toUpperCase()} TAMAMLANDI`;$("#recordLabel").style.color=newRecord?"var(--primary)":"var(--secondary)";$("#gameOverTitle").textContent=summary.mode==="streak"?`${summary.bestPerfectCombo} TAM SERİ`:summary.perfect>=5?"ZAMAN USTASI":summary.bestCombo>=5?"RİTMİ YAKALADIN":"BİR DAHA!";$("#finalScore").textContent=summary.score.toLocaleString("tr-TR");$("#summaryRound").textContent=summary.round;$("#summaryCombo").textContent=summary.mode==="streak"?summary.bestPerfectCombo:summary.bestCombo;$("#summaryPerfect").textContent=summary.perfect;$("#summaryAverage").textContent=summary.average?`${summary.average} ms`:"—";$("#performanceNote").textContent=summary.best?`En iyi dokunuşun ${summary.best} ms farktaydı.`:summary.early>summary.late?"Hızlısın; biraz daha sabır skorunu yükseltebilir.":summary.late>summary.early?"Geç dokunuşların daha fazla; hedefi biraz önce sez.":"Hareketin ritmini izle ve hedef anına odaklan.";showScreen("gameOver");
}
async function resumeCountdown(){$("#pauseOverlay").classList.remove("show");const count=$("#countIn");count.classList.add("show");for(const value of["3","2","1"]){count.textContent=value;feedback.tone("start");await new Promise(resolve=>setTimeout(resolve,data.reducedMotion?180:430));}count.classList.remove("show");}
function pauseGame(){if(!game.active||game.paused)return;game.pause();$("#pauseOverlay").classList.add("show");}
function copyText(text){if(navigator.clipboard?.writeText)return navigator.clipboard.writeText(text);const area=document.createElement("textarea");area.value=text;document.body.appendChild(area);area.select();document.execCommand("copy");area.remove();return Promise.resolve();}
function shareCard(summary){return new Promise(resolve=>{const canvas=document.createElement("canvas");canvas.width=1080;canvas.height=1080;const c=canvas.getContext("2d"),gradient=c.createLinearGradient(0,0,1080,1080);gradient.addColorStop(0,"#04111f");gradient.addColorStop(1,"#0a3b35");c.fillStyle=gradient;c.fillRect(0,0,1080,1080);c.strokeStyle="#55dec1";c.lineWidth=14;c.beginPath();c.arc(540,300,125,0,Math.PI*2);c.stroke();c.strokeStyle="#48e39b";c.beginPath();c.arc(540,300,75,0,Math.PI*2);c.stroke();c.fillStyle="#fff";c.beginPath();c.arc(540,300,18,0,Math.PI*2);c.fill();c.textAlign="center";c.font="900 86px system-ui";c.fillText("TAM İSABET",540,525);c.fillStyle="#65efad";c.font="900 120px system-ui";c.fillText(summary.score.toLocaleString("tr-TR"),540,690);c.fillStyle="#fff";c.font="600 38px system-ui";c.fillText(`${MODE_NAMES[summary.mode]} · ${summary.perfect} Tam İsabet`,540,780);canvas.toBlob(resolve,"image/png");});}

$("#startBtn").addEventListener("click",()=>startMode("classic"));$("#tutorialBtn").addEventListener("click",()=>showScreen("tutorial"));$("#settingsBtn").addEventListener("click",()=>{applySettings();showScreen("settings");});$("#statsBtn").addEventListener("click",()=>{renderStats();showScreen("stats");});$("#modesBtn").addEventListener("click",()=>showScreen("modes"));$("#beginTutorialBtn").addEventListener("click",startTutorial);$("#replayTutorialBtn").addEventListener("click",startTutorial);$$('[data-back]').forEach(button=>button.addEventListener("click",()=>showScreen("menu")));$$('[data-mode]').forEach(button=>button.addEventListener("click",()=>startMode(button.dataset.mode)));
$("#pauseBtn").addEventListener("click",event=>{event.stopPropagation();pauseGame();});$("#resumeBtn").addEventListener("click",()=>game.resume(resumeCountdown));$("#quitBtn").addEventListener("click",()=>{game.stop();$("#pauseOverlay").classList.remove("show");showScreen("menu");});$("#replayBtn").addEventListener("click",()=>startMode(currentMode));$("#menuBtn").addEventListener("click",()=>showScreen("menu"));
[["sound","soundEnabled"],["vibration","vibrationEnabled"],["contrast","highContrast"],["motion","reducedMotion"]].forEach(([name,key])=>{$(`#${name}Toggle`).addEventListener("change",event=>{data[key]=event.target.checked;if(key==="soundEnabled")feedback.unlock();applySettings();persist();});});$$('button[data-theme]').forEach(button=>button.addEventListener("click",()=>{data.theme=button.dataset.theme;applySettings();persist();toast("Tema uygulandı");}));$$('[data-target]').forEach(button=>button.addEventListener("click",()=>{data.targetStyle=button.dataset.target;applySettings();persist();toast("Hedef tasarımı uygulandı");}));
$("#quickSoundBtn").addEventListener("click",()=>{data.soundEnabled=!data.soundEnabled;if(data.soundEnabled)feedback.unlock();applySettings();persist();toast(data.soundEnabled?"Ses açıldı":"Ses kapatıldı");});$("#resetStatsBtn").addEventListener("click",()=>{if(!confirm("Tüm oyun istatistikleri sıfırlansın mı?"))return;resetStats(data);ensureDailyTask();renderStats();applySettings();toast("İstatistikler sıfırlandı");});
$("#shareBtn").addEventListener("click",async()=>{if(!lastSummary)return;const text=`Tam İsabet'te ${lastSummary.score.toLocaleString("tr-TR")} puan yaptım. En iyi dokunuşum ${lastSummary.best||0} ms farktaydı. Sen daha iyisini yapabilir misin?`;try{const blob=await shareCard(lastSummary),file=new File([blob],"tam-isabet-skor.png",{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({title:"Tam İsabet",text,files:[file]});else if(navigator.share)await navigator.share({title:"Tam İsabet",text,url:location.href});else{await copyText(text);toast("Skor metni panoya kopyalandı");}}catch(error){if(error.name!=="AbortError")toast("Paylaşım tamamlanamadı");}});
document.addEventListener("visibilitychange",()=>{if(document.hidden)pauseGame();});window.addEventListener("resize",()=>{document.documentElement.style.setProperty("--app-height",`${window.innerHeight}px`);if(matchMedia("(orientation: landscape) and (max-height: 600px)").matches)pauseGame();});document.addEventListener("pointerdown",()=>feedback.unlock(),{once:true});document.documentElement.style.setProperty("--app-height",`${window.innerHeight}px`);ensureDailyTask();applySettings();persist();
if(location.protocol==="http:"||location.protocol==="https:"){const manifest=document.createElement("link");manifest.rel="manifest";manifest.href="./manifest.webmanifest";document.head.appendChild(manifest);}if("serviceWorker"in navigator&&(location.protocol==="http:"||location.protocol==="https:"))window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));
})();