const assert=require("node:assert/strict");
global.window={};global.ResizeObserver=class{observe(){}};global.cancelAnimationFrame=()=>{};global.requestAnimationFrame=()=>1;global.getComputedStyle=()=>({getPropertyValue:()=>"#fff"});global.document={documentElement:{}};
require("../js/rounds.js");require("../js/game.js");
const noop=()=>{},classList={add:noop,remove:noop,toggle:noop},ctx={clearRect:noop,save:noop,restore:noop,setTransform:noop};
function elements(){return{canvas:{getContext:()=>ctx,width:0,height:0},arena:{addEventListener:noop,getBoundingClientRect:()=>({width:390,height:600}),classList},score:{},round:{},combo:{},comboFill:{style:{}},energy:{children:[{classList},{classList},{classList}],classList,setAttribute:noop},timer:{classList},modeLabel:{},resultCard:{},missionCard:{classList},missionKicker:{},missionText:{},roundType:{},resultLabel:{},resultTiming:{},resultPoints:{}};}
function game(){return new window.TamGame({elements:elements(),data:{gamesByMode:{},roundTypeCounts:{},reducedMotion:true},feedback:{unlock:noop,tone:noop,result:noop,vibrate:noop},onFinish:noop,onStatsChange:noop});}
let state=42;const random=()=>((state=Math.imul(state,1664525)+1013904223>>>0)/4294967296);const g=game();g.mode="classic";g.randomSource=random;const ids=[],totalTypes=window.TamRounds.roundTypes.length;for(let round=1;round<=totalTypes+20;round++){g.round=round;ids.push(g.getRoundType().id);}assert.equal(new Set(ids).size,window.TamRounds.roundTypes.length,"Tüm tur türleri seçilmeli");assert.equal(new Set(ids.slice(0,window.TamRounds.roundTypes.length)).size,window.TamRounds.roundTypes.length,"Aynı oturumda havuz bitmeden tur tekrarlanmamalı");for(let i=1;i<ids.length;i++)assert.notEqual(ids[i],ids[i-1],"Arka arkaya aynı tur gelmemeli");for(let i=4;i<ids.length;i++)assert.ok(!ids.slice(i-3,i).includes(ids[i]),"Son üç tur kısa aralıkta tekrar etmemeli");
function dailySequence(){const d=game();d.start({mode:"daily",seed:"2026-07-29"});const seq=[];for(let i=0;i<12;i++){seq.push([d.currentType.id,d.config.variant,Math.round(d.duration)]);clearTimeout(d.missionTimer);cancelAnimationFrame(d.raf);if(i<11)d.nextRound();}d.stop();return seq;}assert.deepEqual(dailySequence(),dailySequence(),"Günlük seri aynı seed ile aynı olmalı");
const once=game();once.active=true;once.paused=false;once.currentType={id:"test",draw:noop};once.duration=1000;once.startTime=0;once.targetTime=1000;once.timeoutTime=1500;once.lastFrame=0;once.locked=false;once.evaluated=false;once.lives=3;once.frame(1600);once.frame(1616);assert.equal(once.lives,2,"Bir tur yalnızca bir enerji tüketmeli");assert.equal(once.history.length,1,"Bir tur yalnızca bir kez değerlendirilmeli");clearTimeout(once.nextTimer);
const pendulumAngle=window.TamRounds.helpers.pendulumAngle;for(let i=0;i<100;i++){const p=i/100;assert.ok(pendulumAngle(p)>0,"Sarkaç hedef öncesinde merkezi kesmemeli");}assert.ok(Math.abs(pendulumAngle(1))<1e-9,"Sarkaç yalnızca hedef anında merkezde olmalı");
const squareAlignmentAngle=window.TamRounds.helpers.squareAlignmentAngle;for(let i=0;i<100;i++){const angle=Math.abs(squareAlignmentAngle(i/100));assert.ok(angle>0&&angle<Math.PI/2,"Dönen kare hedef öncesinde eşleşmemeli");}assert.ok(Math.abs(squareAlignmentAngle(1))<1e-9,"Dönen kare yalnızca hedef anında eşleşmeli");
const drawCtx=new Proxy({},{get:()=>noop,set:()=>true});for(const type of window.TamRounds.roundTypes){for(const progress of[0,.5,1])type.draw(drawCtx,390,600,progress,1000,{primary:"#48e39b",secondary:"#55dec1",accent:"#21b98f",danger:"#ff6278",duration:2400,config:{variant:2,size:.5,targetStyle:"orbit"},difficulty:12});}
console.log(`PASS: ${new Set(ids).size} tur türü, tüm çizimler, tekrar koruması, günlük seed ve tek değerlendirme`);